### ISSUE TITLE
Sanitise field output

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#12]
https://github.com/redacademy/clt-summer-2018/blob/be8603c273ffb83ae9a127faf35530378bf0217f/themes/community-land-trust/page-templates/contact.php#L23-L31

You should sanitise the output of custom fields to be compliant with security best practices.

Try adding some script to your custom fields to see the vulnerability e.g. try adding:
```<script>alert('This field is Vulnerable to Cross-site scripting (XSS)');</script>```
Then when you visit the front-end of the page with the field you will see the JavaScript runs.

A simple fix is to sanitize output using some of the WordPress methods. You can simply wrap CFS->get method like so:

```echo esc_html(CFS()->get('subtitle'));```

Please review the lesson material for more info as to which methods you can use: https://red-wdp.herokuapp.com/slides/wp-security-deployment-and-hosting-slides/#8

**Comment by jaridnft** [comment]
Thanks for bringing this to our attention.

I've sanitized pages I wrote (`archive-portfolio.php`, `page-templates/find.php`, and `single-portfolio.php`) on commit 82e63b46a84f4a4e39ceb3b20c7d5e52c378e3a6

**Comment by jaridnft** [comment]
Going to close this, only CFS() calls should be escaped by WordPress with output 'text' fields.
