### ISSUE TITLE
Consider changing map-canvas to be a class

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#13]
https://github.com/redacademy/clt-summer-2018/blob/be8603c273ffb83ae9a127faf35530378bf0217f/themes/community-land-trust/src/js/map-functionality.js#L10

You could use a class here instead of an ID (and then remove the references to ID in your CSS).

**Comment by jaridnft** [comment]
I tried to do this originally, but the Google API didn't work unless this was an ID.
