### ISSUE TITLE
Add screenshot to theme

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#14]
Please add a theme screenshot, even if the sites not done you might as well update this even if it's just an image with the theme name on it.

If you don't have Photoshop you can generate a new image with text at: https://dummyimage.com/

**Comment by jaridnft** [comment]
Added with 63c0c1cb83368c44296068175fdbb1ed8845f6bb, but will need to be updated when CTA positioning is fixed.

**Comment by jaridnft** [comment]
Updated with 35b4c8f16e53f3b5711f1e935f512254169261d3
