### ISSUE TITLE
Styling of portfolio buttons in Firefox

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#15]
The styling of these buttons is a little wrong in Firefox. 
<img width="510" alt="screen shot 2018-09-13 at 10 54 14" src="https://user-images.githubusercontent.com/5031585/45506213-734e4000-b743-11e8-9d30-de0bb5f7029b.png">

**Comment by jaridnft** [comment]
These were broken due to a mixin over-riding styles, and has been fixed since at latest a0e2004584f133928451544a7e80603ced082915
