### ISSUE TITLE
"Need more information" styling in Firefox

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#16]
The styling of the "Need more information" section at the bottom of the page is broken in Firefox on various pages. 

<img width="1270" alt="screen shot 2018-09-13 at 10 56 26" src="https://user-images.githubusercontent.com/5031585/45506348-c7f1bb00-b743-11e8-9be4-ca5bd708d2cb.png">

**Comment by jaridnft** [comment]
Fixed on a48cb28a3c0b5e30bcd16c46f7eb9e5cfe6ebf2c
