### ISSUE TITLE
counterup doesn't seem to be working

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#17]
https://github.com/redacademy/clt-summer-2018/blob/4b83a3ccdc0e4f5121e851d9a881d92bed12edd2/themes/community-land-trust/src/js/counter-up.js#L2

Looks like you need to change this to use `.timeline-growth-numbers` rather than `.counter`

**Comment by jaridnft** [comment]
Fixed in f0381eee6503b8487c92eec096471deb8a24e9c1
