### ISSUE TITLE
Missing README file

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#2]
The repo should have a README file at the root which details the following:

- Brief description of the project
- Instructions for setting up the project (including plugins and any other dependencies)
- Any other information that would be useful for someone using your code in the future

**Comment by benorgan** [comment]
Also you might want to remove / update README.md in the /themes/community-land-trust directory

**Comment by jaridnft** [comment]
Removed `/themes/community-land-trust/README.md` and added `./README.md` (will fill out later) on commit a2d0edfc72e0375f96939754e1393c678e6b461e

**Comment by jaridnft** [comment]
Added with c6738164ec3290c7a942d1474db0568f0747e67f
