### ISSUE TITLE
Google Map URL could be a CFS field

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#3]
https://github.com/redacademy/clt-summer-2018/blob/5c29a3923dabaf21b5eb6fe395b1de60087143ba/themes/community-land-trust/page-templates/contact.php#L35

This URL might need to be changed in the future, could make it a CFS hyperlink field.

**Comment by benorgan** [comment]
You have the same issue here: themes/community-land-trust/footer.php

**Comment by jaridnft** [comment]
Closing this as we use a real map on the Contact page now. 

CFS fields for the footer are tricky. We don't have a 'page' to assign it to, since the footer is called everywhere. Any suggestions?

**Comment by benorgan** [comment]
For the CFS fields in the footer I believe these are contact information? Therefore it would make sense to attach the to the contact page, even if the fields aren't visible on that page itself.
