### ISSUE TITLE
Error styling on contact form

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#4]
When there are validation errors on the contact form the styling is incorrect

**Comment by benorgan** [comment]
This seems to be fine in Firefox, but is wrong in Chrome.

**Comment by benorgan** [comment]
Looks like this is now resolved?

**Comment by jaridnft** [comment]
Contact form is still in progress; will keep this open until it's finished.

**Comment by jaridnft** [comment]
Don't know when this was officially fixed (commit hash), but as of this comment this is fixed.
