### ISSUE TITLE
Image tags don't need to be closed

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#6]
https://github.com/redacademy/clt-summer-2018/blob/451e3a8a5d5e4e2451519ba7bd25e958d005c9c4/themes/community-land-trust/archive-partner.php#L28

</img> is not required

**Comment by benorgan** [comment]
You have the same issue here: themes/community-land-trust/page-templates/about.php

**Comment by vbertoletti** [comment]
Thank you, issue has been solved in both php files.
