### ISSUE TITLE
Remove commented out code

### ISSUE THREAD

**Issue by benorgan** [redacademy/clt-summer-2018#9]
https://github.com/redacademy/clt-summer-2018/blob/d15337048207362e27b64814ced3cf498e913c5d/themes/community-land-trust/src/scss/_about.scss#L34-L40

If code isn't needed then delete it rather than commenting it out (or at least leave a message to explain why it's commented out).

**Comment by vbertoletti** [comment]
It was removed after problem solving, thank you.

**Comment by jaridnft** [comment]
Please include the commit hash for reference when solving an issue.
